-- =====================================================================
-- Migration: Initial Database Schema for 10x-cards
-- Description: Creates core tables for flashcard application with SM-2 algorithm support
-- Author: Generated via Claude Code
-- Date: 2026-01-10
--
-- Tables affected:
--   - public.profiles (user profile with AI generation limits)
--   - public.decks (flashcard decks)
--   - public.cards (individual flashcards with SM-2 parameters)
--
-- Types created:
--   - public.card_status (enum: unverified, accepted)
--
-- Special notes:
--   - All tables have RLS enabled with granular policies
--   - owner_id is denormalized in cards for RLS performance
--   - SM-2 algorithm parameters stored as integers (ease_factor_x100)
--   - AI generation limits tracked per day in Europe/Warsaw timezone
-- =====================================================================

-- =====================================================================
-- 1. CREATE ENUM TYPES
-- =====================================================================

-- create enum type for card verification status
-- unverified: card generated by AI, awaiting user review
-- accepted: card approved by user and ready for spaced repetition
create type public.card_status as enum ('unverified', 'accepted');

-- =====================================================================
-- 2. CREATE TABLE: public.profiles
-- =====================================================================

-- user profile table (1:1 with auth.users)
-- stores AI generation limits and usage tracking
-- limits are reset daily based on Europe/Warsaw timezone
create table public.profiles (
    -- primary key references auth.users for 1:1 relationship
    id uuid primary key references auth.users(id) on delete cascade,

    -- timestamp when profile was created
    created_at timestamptz not null default now(),

    -- date of last AI generation (Europe/Warsaw timezone)
    -- used to determine if daily limit should be reset
    -- null means user has never generated cards
    ai_generation_date date null,

    -- number of AI generations performed on ai_generation_date
    -- resets to 1 when date changes, increments up to 5 per day
    ai_generation_count integer not null default 0
        check (ai_generation_count >= 0 and ai_generation_count <= 5)
);

-- enable row level security on profiles
alter table public.profiles enable row level security;

-- =====================================================================
-- 3. CREATE TABLE: public.decks
-- =====================================================================

-- flashcard deck table
-- each deck belongs to one user and contains multiple cards
-- tracks last usage for sorting in UI
create table public.decks (
    -- unique identifier for the deck
    id uuid primary key default gen_random_uuid(),

    -- foreign key to user who owns this deck
    -- cascade delete ensures orphaned decks are removed
    owner_id uuid not null references auth.users(id) on delete cascade,

    -- human-readable deck name (1-100 characters required)
    name text not null check (char_length(name) >= 1 and char_length(name) <= 100),

    -- timestamp when deck was created
    created_at timestamptz not null default now(),

    -- timestamp when deck was last accessed (for sorting)
    -- updated when review session starts or other deck interactions
    last_used_at timestamptz not null default now()
);

-- enable row level security on decks
alter table public.decks enable row level security;

-- =====================================================================
-- 4. CREATE TABLE: public.cards
-- =====================================================================

-- individual flashcard with front/back content and SM-2 algorithm state
-- each card belongs to one deck and tracks its review schedule
-- owner_id is denormalized from deck for RLS performance
create table public.cards (
    -- unique identifier for the card
    id uuid primary key default gen_random_uuid(),

    -- foreign key to parent deck
    -- cascade delete ensures cards are removed with deck
    deck_id uuid not null references public.decks(id) on delete cascade,

    -- denormalized owner for RLS performance
    -- must match deck.owner_id (enforced in application logic)
    owner_id uuid not null references auth.users(id) on delete cascade,

    -- front side of flashcard (question/prompt)
    -- trimmed length must be 1-200 characters
    front text not null check (char_length(trim(front)) > 0 and char_length(front) <= 200),

    -- back side of flashcard (answer/explanation)
    -- trimmed length must be 1-500 characters
    back text not null check (char_length(trim(back)) > 0 and char_length(back) <= 500),

    -- verification status (unverified = AI-generated awaiting review, accepted = ready for SRS)
    status public.card_status not null default 'unverified',

    -- timestamp when card was created
    created_at timestamptz not null default now(),

    -- timestamp when card was last modified (front, back, or status)
    updated_at timestamptz not null default now(),

    -- ===== SM-2 Algorithm Parameters =====

    -- scheduled date/time for next review
    -- null for unverified cards, set to now() when accepted
    next_review_at timestamptz null,

    -- current interval between reviews in days (SM-2 parameter)
    -- starts at 0, increases based on quality of recall
    interval_days integer not null default 0 check (interval_days >= 0),

    -- number of consecutive successful reviews (SM-2 parameter)
    -- resets to 0 on failed review
    repetitions integer not null default 0 check (repetitions >= 0),

    -- ease factor multiplied by 100 to avoid floating point (SM-2 parameter)
    -- 250 = 2.50 (default), minimum 130 = 1.30
    -- adjusted based on recall quality
    ease_factor_x100 integer not null default 250 check (ease_factor_x100 >= 130),

    -- timestamp of most recent review
    -- null means never reviewed
    last_reviewed_at timestamptz null
);

-- enable row level security on cards
alter table public.cards enable row level security;

-- =====================================================================
-- 5. CREATE INDEXES
-- =====================================================================

-- index for fetching user's decks sorted by last usage (hot path)
-- used in main deck list view
create index idx_decks_owner_last_used
    on public.decks (owner_id, last_used_at desc);

-- index for fetching cards from deck filtered by status
-- used when displaying deck contents
create index idx_cards_deck_status
    on public.cards (deck_id, status);

-- partial index for due cards queries (cards ready for review)
-- only indexes accepted cards with scheduled review time
-- used to find cards where next_review_at <= now()
create index idx_cards_deck_due
    on public.cards (deck_id, status, next_review_at)
    where status = 'accepted' and next_review_at is not null;

-- index for RLS policies filtering by owner
-- improves performance of user-scoped queries
create index idx_cards_owner
    on public.cards (owner_id);

-- =====================================================================
-- 6. ROW LEVEL SECURITY POLICIES
-- =====================================================================

-- ---------------------------------------------------------------------
-- 6.1 Policies for public.profiles
-- ---------------------------------------------------------------------

-- authenticated users can read their own profile
-- uses auth.uid() which returns the authenticated user's id
create policy profiles_select_authenticated on public.profiles
    for select
    to authenticated
    using (auth.uid() = id);

-- authenticated users can create their own profile during registration
-- ensures users can only create profile with their own user id
create policy profiles_insert_authenticated on public.profiles
    for insert
    to authenticated
    with check (auth.uid() = id);

-- authenticated users can update their own profile
-- both using and with check clauses ensure ownership
create policy profiles_update_authenticated on public.profiles
    for update
    to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);

-- ---------------------------------------------------------------------
-- 6.2 Policies for public.decks
-- ---------------------------------------------------------------------

-- authenticated users can select only their own decks
-- filters rows where owner_id matches authenticated user
create policy decks_select_authenticated on public.decks
    for select
    to authenticated
    using (auth.uid() = owner_id);

-- authenticated users can insert decks only for themselves
-- enforces that new decks have owner_id set to authenticated user
create policy decks_insert_authenticated on public.decks
    for insert
    to authenticated
    with check (auth.uid() = owner_id);

-- authenticated users can update only their own decks
-- using clause filters existing rows, with check validates new values
create policy decks_update_authenticated on public.decks
    for update
    to authenticated
    using (auth.uid() = owner_id)
    with check (auth.uid() = owner_id);

-- authenticated users can delete only their own decks
-- cascade delete will automatically remove associated cards
create policy decks_delete_authenticated on public.decks
    for delete
    to authenticated
    using (auth.uid() = owner_id);

-- ---------------------------------------------------------------------
-- 6.3 Policies for public.cards
-- ---------------------------------------------------------------------

-- authenticated users can select only their own cards
-- uses denormalized owner_id for efficient filtering without joins
create policy cards_select_authenticated on public.cards
    for select
    to authenticated
    using (auth.uid() = owner_id);

-- authenticated users can insert cards only for themselves
-- application logic must ensure owner_id matches deck.owner_id
create policy cards_insert_authenticated on public.cards
    for insert
    to authenticated
    with check (auth.uid() = owner_id);

-- authenticated users can update only their own cards
-- protects against unauthorized modifications of card content or state
create policy cards_update_authenticated on public.cards
    for update
    to authenticated
    using (auth.uid() = owner_id)
    with check (auth.uid() = owner_id);

-- authenticated users can delete only their own cards
-- supports both hard delete of individual cards and cascade from deck deletion
create policy cards_delete_authenticated on public.cards
    for delete
    to authenticated
    using (auth.uid() = owner_id);

-- =====================================================================
-- END OF MIGRATION
-- =====================================================================
